### PR TITLE
put Other install guides at the end after Monitoring

### PR DESCRIPTION
**Pull request by DrDaveD**

### CODE REVIEW

**Comment by brianhlin** [comment]
@DrDaveD Could you handle the merge conflicts?

**Comment by DrDaveD** [comment]
@brianhlin Ok, merge conflicts handled

**Comment by DrDaveD** [comment]
Ok, it is reverted.

**Comment by DrDaveD** [comment]
I am mostly OK with them.  Pretty extensive changes though, and they'll need to be applied to the other pages as well.  I had noticed the ::console in other pages but couldn't get it to work, I think because I was accidentally trying three colons.  I had put in the `<br>` lines after code blocks because that was the only way I could get it to put enough whitespace there.  It looks OK on this page but might be a problem on the cvmfs page.

One questions, though: Is it really necessary to tell people to do a complete wipe of their yum cache and update of all rpms just to install frontier-squid?  I think that's a bit much.

**Pull request merged**
