### PR TITLE
Review of Singularity installation document

### PR DESCRIPTION
**Pull request by djw8605**
- Though noted that no site is ready to run non-setuid singularity,
  it was at the top of the document.  I moved it to below the
  production instructions.
- Fixed minor typo of the date.
- Added note to install CVMFS in order to validate the installation.

### CODE REVIEW

**Comment by DrDaveD** [comment]
@djw8605 Hold on! You asked for my review and then didn't wait for it.  I don't agree with the changes.  Does @bbockelm agree with the changes?  He was quite involved with the current document.

We had the order this way because we want to push things in the direction of unprivileged.  If we have to have the privileged one first, then I at least one to see a variation on the big 'As of December 2017' note at the beginning of the privileged section or just before it, to explain to people that the other kind follows and they might want to do both but for now they need to at least do the first one because that's what the VOs need.

**Comment by djw8605** [comment]
I can't imagine sending the previous documentation to a site, saying "Install Singularity", when it includes changing grub entries as the top instructions.  I have a hard time justifying that to sites that want to install Singularity for the fist time.

The top paragraphs on the page deeply explain the non-setuid situation.  I can add another "note" or "tip" on the top.

**Comment by DrDaveD** [comment]
Please do add a note at the beginning or just before the privileged install, and remove the one at the beginning of the unprivileged install.

**Comment by brianhlin** [comment]
I don't see any harm in keeping the note at the top of the unpriv section

**Comment by DrDaveD** [comment]
Well my intention is to give people the information to decide up front before they begin the installation, so then it would be redundant to have it again in the second section.  Maybe just have a short reminder.

**Comment by djw8605** [comment]
I count 3 notes in the first section.  I'll try to work out the text a bit.

**Pull request merged**
