### PR TITLE
Add Singularity requirement

### PR DESCRIPTION
**Pull request by brianhlin**

### CODE REVIEW

**Comment by brianhlin** [comment]
@rynge I think this is something that we had discussed since all the current COVID projects require singularity?

**Comment by brianhlin** [comment]
@rynge I'm catching up on old PRs. Should we merge the Singularity requirement or abandon it?

**Comment by rynge** [comment]
Singularity tests will not pass without CVMFS being available. I think we should to:

OPTIONAL: CVMFS and Singularity will increase the number of jobs which can run on the site

**Comment by brianhlin** [comment]
Force push to fix a typo in the commit to add the CVMFS recommendation and note that both it and Singularity are optional

**Pull request merged**
