### PR TITLE
Migrate low prio release3 docs (various)

### PR DESCRIPTION
**Pull request by edquist**
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/AutoPyFactory

- [ ] Enter date into "Migrated" column of google sheet
- [ ] Add migration header to TWiki document

---

https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/AutoPyFactoryConfiguration

- [ ] Enter date into "Migrated" column of google sheet
- [ ] Add migration header to TWiki document

---

https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/AutoPyFactoryDeployment

- [ ] Enter date into "Migrated" column of google sheet
- [ ] Add migration header to TWiki document

---

https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/BanningUsersAtSite

- [ ] Enter date into "Migrated" column of google sheet
- [ ] Add migration header to TWiki document

---

https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/BestmanGridftpPathPlugin

- [ ] Enter date into "Migrated" column of google sheet
- [ ] Add migration header to TWiki document

---

https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/CertificateUserGet

- [ ] Enter date into "Migrated" column of google sheet
- [ ] Add migration header to TWiki document

---

https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/GetHostServiceCertificatesWeb

- [ ] Enter date into "Migrated" column of google sheet
- [ ] Add migration header to TWiki document

---

https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/GlexecPilotCert

- [ ] Enter date into "Migrated" column of google sheet
- [ ] Add migration header to TWiki document

---

https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/GlideinWMSCampusGrid

- [ ] Enter date into "Migrated" column of google sheet
- [ ] Add migration header to TWiki document

---

https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/GratiaTransferProbe

- [ ] Enter date into "Migrated" column of google sheet
- [ ] Add migration header to TWiki document

---

https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/HadoopDebug

- [ ] Enter date into "Migrated" column of google sheet
- [ ] Add migration header to TWiki document

---

https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/HadoopRecovery

- [ ] Enter date into "Migrated" column of google sheet
- [ ] Add migration header to TWiki document

---

https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/InstallGlideinWMSFactory

- [ ] Enter date into "Migrated" column of google sheet
- [ ] Add migration header to TWiki document

---

https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/InstallGridFtpXrootd

- [ ] Enter date into "Migrated" column of google sheet
- [ ] Add migration header to TWiki document

---

https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/InstallHadoopSE

- [ ] Enter date into "Migrated" column of google sheet
- [ ] Add migration header to TWiki document

---

https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/LocalStorageConfiguration

- [ ] Enter date into "Migrated" column of google sheet
- [ ] Add migration header to TWiki document

---

https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/NetworkPerformanceToolkit

- [ ] Enter date into "Migrated" column of google sheet
- [ ] Add migration header to TWiki document

---

https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/OsgCaManage

- [ ] Enter date into "Migrated" column of google sheet
- [ ] Add migration header to TWiki document

---

https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/ReleaseNotes

- [ ] Enter date into "Migrated" column of google sheet
- [ ] Add migration header to TWiki document

---

https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/SrmTester

- [ ] Enter date into "Migrated" column of google sheet
- [ ] Add migration header to TWiki document

---

### CODE REVIEW

**Comment by brianhlin** [comment]
Could you actually delete the following docs:

- `docs/other/autopy-factor.md`
- `docs/other/autopy-factory-config.md`
- `docs/other/autopy-factory-deployment.md`

I'm still working out how we want to handle all the AutoPyFactory* docs (we still want to archive them so you can keep what's in `archive/`

**Comment by bbockelm** [comment]
I don't understand this PR.

For archive-only docs, I'm OK with big giant PRs moving them from point-A to point-B.

But if we're going to add content and expect real reviews, we should do things one-at-a-time.  Seems like some of these docs aren't converted as much as simply run through `pandoc` and committed.

Even low-priority docs should render well and be included in the `mkdocs.yml`.  If they're low-priority enough to not put them in the table of contents, then they don't need to be converted to markdown -- they can just live in the archive.

(Hm -- we should probably have a Travis-CI check to verify that all `*.md` docs are listed in `mkdocs.yml`.)

**Comment by edquist** [comment]
@brianhlin had asked to just get all these low-prio docs into a single big PR, though it was understood that this initial migration of them would not yet be tidied up.  @brianhlin, please clarify if you have any thoughts on this...

**Comment by brianhlin** [comment]
@edquist there have been some developments on the Oct 1 deadline, namely that we will be able to add migration headers after the fact so this mass migration isn't pressing (I would still like the migration/archival tools that do not perform any git actions).

**Pull request closed without merging**
