### PR TITLE
Flesh out HTCondor-CE 5 update sections

### PR DESCRIPTION
**Pull request by brianhlin**
I'd like to send an email this week asking that HTCondor-CE admins start upgrading

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Why do people have to add mappings by hand? Can't they use [osg-scitokens-mapfile](https://koji.chtc.wisc.edu/koji/packageinfo?packageID=500)?

**Comment by brianhlin** [comment]
They may map to different local user accounts. I can mark that step as optional, requiring it only for sites that support OSG/GLOW and map them to accounts other than `osg` or `glow`

**Comment by matyasselmeci** [comment]
Can people override mappings in the scitokens mapfile, like they could in the voms-mapfile?

**Comment by brianhlin** [comment]
Not override per se but the lines in `/etc/condor-ce/mapfiles.d/` are used for matching before any lines in `/usr/share/condor-ce/mapfiles.d/` so this setup is analogous to `/etc/grid-security/voms-mapfile` and `/usr/share/osg/voms-mapfile-default`

**Review by matyasselmeci — APPROVED** [review]

**Review by timtheisen — APPROVED** [review]
LGTM

**Pull request merged**
