### PR TITLE
Adding mermaid js support

### PR DESCRIPTION
**Pull request by djw8605**
Documented here: https://squidfunk.github.io/mkdocs-material/reference/diagrams/

Do we need to add something to the build?

### CODE REVIEW

**Comment by brianhlin** [comment]
We'd need to update the container version but also since the feature's marked as experimental, I think that we need to either pay the author or wait until it hits a stable release

**Comment by djw8605** [comment]
Mermaid is listed as a "completed" goal, and therefore available to everyone:
https://squidfunk.github.io/mkdocs-material/insiders/#goals-completed

**Comment by brianhlin** [comment]
Oh great, then maybe if you just update the container version, CI will be happy. This would be a major version upgrade, though, so we'd want to spot-check the other pages before merging

**Comment by djw8605** [comment]
The CI failed because of link checker of osgconnect.net, if I'm reading the output correctly.

**Comment by brianhlin** [comment]
Yup, I think it's on @LincolnBryant 's todo list to get the relevant SAN added to the cert.

So I'm fine with the CI failure -- did you spot check the other pages?

**Comment by djw8605** [comment]
Spot checked the other pages.  Fixed a long standing issue with both the production and this new version with un-styled footer prev and next links by using a copyright partial.

**Review by matyasselmeci — APPROVED** [review]

**Pull request merged**
