### PR TITLE
Preliminary release notes for 3.4.10

### PR DESCRIPTION
**Pull request by timtheisen**

### CODE REVIEW

**Comment by DrDaveD** [comment]
@timtheisen Where are the known issues with singularity, I don't see them?

**Comment by timtheisen** [comment]
I am waiting for exact verbiage from from @brianhlin 
There can be a slow startup problem with a large default allowable number of file descriptors:
 https://github.com/singularityware/singularity/issues/1447

**Comment by brianhlin** [comment]
@DrDaveD @timtheisen known issues added

**Comment by timtheisen** [comment]
Those changes look good, Brian

**Pull request merged**
