### PR TITLE
Remove deprecated software

### PR DESCRIPTION
**Pull request by brianhlin**
So long 3.3 and thanks for all the fish

### CODE REVIEW

**Comment by bbockelm** [comment]
Are we going to have to turn around and immediately resurrect the Java docs to support HDFS?

**Comment by matyasselmeci** [comment]
No - the Java docs document a shim that we needed for other components but not HDFS.

**Comment by matyasselmeci** [comment]
Shouldn't we hold off on this until we stop supporting 3.3 for Fermi, too?

**Comment by bbockelm** [comment]
Wonderful!

**Pull request merged**
