### PR TITLE
Clarify round-robin DNS registration

### PR DESCRIPTION
**Pull request by brianhlin**
I think this improves on the previous text by not overloading the word "registration"

### CODE REVIEW

**Comment by brianhlin** [comment]
I see why you had originally put it there but I think it's a little confusing because it seems to indicate that you can list multiple FQDNs in the `FQDN` field, which isn't true.

**Comment by DrDaveD** [comment]
I think it's clear because "name" is still singular.

**Comment by DrDaveD** [comment]
Or you could use fully.qualified.DNS.name.of.your.server.or.round-robin

**Comment by brianhlin** [comment]
I think the latest commits address your wishes while improving the clarity

**Pull request merged**
