### PR TITLE
Update cvmfs documentation to latest version

### PR DESCRIPTION
**Pull request by DrDaveD**
This should be merged after pr #42, that is merged into this pr.

https://twiki.grid.iu.edu/bin/view/Documentation/Release3/InstallCvmfs

- [x] Enter date into "Migrated" column of google sheet
- [ ] Add migration header to TWiki document

### CODE REVIEW

**Comment by brianhlin** [comment]
@DrDaveD could you add [step 4](https://opensciencegrid.github.io/technology/software/markdown-migration/#submitting-the-pull-request) as appropriate to the body of this PR?

**Comment by DrDaveD** [comment]
I updated the worksheet just now, but I don't want to update the twiki link until it is merged.  I'll put it in unchecked for now.

**Comment by DrDaveD** [comment]
@brianhlin Are you going to reformat this one too or must I take a crack at making it like frontier-squid?

**Comment by brianhlin** [comment]
I'm in the middle of working on it as we speak!

**Comment by DrDaveD** [comment]
I inserted a couple more br's but otherwise it's OK to merge.

How do you decide whether to use ::console or triple backquotes or triple backquotes console?  There's so many different ways of doing things.

**Comment by brianhlin** [comment]
In lists, I use `:::console`, otherwise I use triple backquotes console.

**Pull request merged**
