### PR TITLE
Add docpreview script for running mkdocs serve with the appropriate PYTHONPATH

### PR DESCRIPTION
**Pull request by matyasselmeci**

### CODE REVIEW

**Comment by brianhlin** [comment]
Is there a way to find the git clone dir? That way this script could be run from any dir

**Comment by brianhlin** [comment]
Also, maybe this goes better in the `doc-ci-scripts` to make this more widely available?

**Comment by matyasselmeci** [comment]
It would be nice if we put it into doc-ci-scripts, but then it would be in the `ci` folder and harder to find. What do you mean "can be run from any dir"? Currently the source dir it uses in the repo the script itself is in, no matter where you run it from.

**Comment by brianhlin** [comment]
Eh, we could have our docs tell people to run `ci/docpreview` or repo owners could symlink the tool.

**Comment by matyasselmeci** [comment]
OK, I'll try that instead.

**Pull request closed without merging**
