### PR TITLE
Added missing Docker capability flag to enable Singularity

### PR DESCRIPTION
**Pull request by rynge**

### CODE REVIEW

**Comment by brianhlin** [comment]
IIRC, @bbockelm was surprised by this requirement

**Comment by rynge** [comment]
I have verified it is required on a fully upgraded EL7 system

**Review by brianhlin — APPROVED** [review]
LGTM

**Comment by bbockelm** [comment]
Is Singularity working in privileged or unprivileged mode in this case?

**Comment by rynge** [comment]
Privileged. I have not explored unprivileged within Docker.

**Pull request merged**
