### PR TITLE
Create install-gwms-factory.md

### PR DESCRIPTION
**Pull request by llobato**
Adding GlideinWMS factory rpm installation for OSG documentation

### CODE REVIEW

**Comment by bbockelm** [comment]
@brianhlin - what do you think about this one?

I feel a bit mixed.  While improved documentation is always welcome, I don't see much of a use case for doing this within the OSG context.  What site or VO admins would we encourage to follow these directions?

There's a (marginally) stronger use case for having the existing frontend docs as, indeed, the frontend is managed by several non-OSG-staff.

Lorena, what's the motivation for having this here versus the upstream docs?  If it's targeted for OSG Staff, perhaps the technology or operation area docs are a better fit?

**Comment by brianhlin** [comment]
Throwing it in operations seems like a reasonable place if there isn't a place upstream for it

**Comment by mambelli** [comment]
@brianhlin and @bbockelm. The operations documents are not much linked from the other OSG pages (was not immediate to find the pages about RPM packaging in OSG) but we will have direct links from the GlideinWMS web pages and between the documents, so it could be a good place. 
From the GlideinWMS team, our goal is to have installation documents that are clear and visible and to avoid duplication of effort. 
The RPM installation documents had been added to the OSG documentation (Twiki at the time) because the RPMs are distributed via OSG. Anyway, I don't have strong feelings on where each of these 2 documents should reside: could be in the OSG  site administrator documentation, the internal technology documentation or the GlideinWMS website.
Frontends are installed and maintained by a few VOs.
Factories are maintained mainly by OSG and CMS. UChicago used to maintain a Factory, I don't know if they still do. ATLAS (BNL) asked for instructions to install Factory and Frontend via RPM and I referred them to the github source for the Factory (until there is a place for the document). 
I think any stable place that you recommend to publish these documents (Frontend and Factory RPM installation) will be a good fit.

**Comment by brianhlin** [comment]
I would like the frontend doc to remain in this repo since VO admins are likely to install it. Is there somewhere that the factory doc can live upstream?

**Comment by mambelli** [comment]
We maintain http://glideinwms.fnal.gov/
We could put the document there.
Keeping one document in OSG and one in our web would make the documents a
bit different (in term of formatting, how the code is represented, ...).
Will add some extra effort for the users but should not be big.

**Comment by brianhlin** [comment]
After thinking about this a bit more, I'm ok with it going into the [operations repo](https://github.com/opensciencegrid/operations) so we can keep the `docs/` repo targeted at the average site admin and you guys don't have to spend too much time on fixing up the formatting. @llobato could you resubmit this as a PR to the operations web? I'll make a `docs/services/` for you to place it in.

**Pull request closed without merging**
