### PR TITLE
Add blahp to 3.5.22 upcoming release

### PR DESCRIPTION
**Pull request by timtheisen**

### CODE REVIEW

**Comment by brianhlin** [comment]
Should we do a new release for this? We didn't mention this change in `upcoming` in the announcement

**Comment by timtheisen** [comment]
I don't think that releasing this one package warrants an entire release. blahp 1.18.47 was released (for 3.5) and described in these release notes. There isn't a separate JIRA ticket.

**Comment by brianhlin** [comment]
> I don't think that releasing this one package warrants an entire release.

As long as we're doing point releases, I disagree. Especially since in release announcements you normally note that a given package is released for both 3.5 and upcoming.

**Comment by timtheisen** [comment]
Of course, an announcement will go out about blahp being placed in upcoming. I've already released it. If we want to make a 3.5.23, then I have to build tarballs, and a bunch of additional work. At least, right now, people won't run into problems installing HTCondor 8.9.7.

**Comment by timtheisen** [comment]
Travis error unrelated

**Pull request merged**
