### PR TITLE
Adding CVMFS LIGO authentication for EGI

### PR DESCRIPTION
**Pull request by efajardo**

### CODE REVIEW

**Comment by efajardo** [comment]
@DrDaveD This is the recipe I have been using at the EGI sites. What do you think?

**Comment by brianhlin** [comment]
Pushing back again: if this is solely for EGI sites, wouldn't it be more appropriate for the EGI documentation?

**Comment by efajardo** [comment]
@brianhlin  Well this gets tricky whichever you slice it. `cvmfs-x509-helper` is maintained by OSG but needs to be installed in sites that support LIGO. However due to them using a different cert bundle and not `oasis` config then extra steps are needed. I can ask if this could be moved [here](https://cvmfs.readthedocs.io/en/stable/cpt-plugins.html#authorization-helpers). But I do not see what is the problem on hosting this documentation here. I mean I can just put into my own github.

**Comment by brianhlin** [comment]
I think it's fine for us to depend on packages maintained by EGI and vice-versa. I think it gets problematic if their sites are depending on our repositories or on us for EGI-only documentation. We aren't in any position to tell EGI sites what to do.

So are they getting `cvmfs-x509-helper` from our repos?

**Comment by efajardo** [comment]
@brianhlin I think so yes

**Comment by brianhlin** [comment]
Yeah, I'm not a fan of that. Can we instead get this added to the EGI repos and have this doc live there (or in the CVMFS helpers doc)

**Comment by DrDaveD** [comment]
It is available in cvmfs-contrib.  Maybe they get it from there.

Currently cvmfs-x509-helper is only used by ligo.osgstorage.org.  EGI doesn't have any of their own repositories for data analogous to any osgstorage.org repository yet.  It's tricky to say where they should get the software from.  I don't think it's so inappropriate to host documentation for it at OSG since that's the source of the repository.

cvmfs-contrib does not have a central documentation place, it just has github repos under https://github.com/cvmfs-contrib that some packages use for documentation.  It's possible to put some documentation there under cvmfs-x509-helper.  I don't think cvmfs wants to document this since it is a contrib package.  I don't know if there is a good place where EGI's UMD hosts install documentation; I haven't seen any.

**Comment by efajardo** [comment]
@djw8605 can I move this documentation to the `cvmfs-x500-helper` readme on the repo?

**Comment by djw8605** [comment]
Sure!

**Comment by brianhlin** [comment]
We decided against adding this to the OSG documentation. It will be going into one of the repos here: https://github.com/cvmfs-contrib/

**Pull request closed without merging**
