### PR TITLE
frontier squid review (SOFTWARE-3075)

### PR DESCRIPTION
**Pull request by edquist**

### CODE REVIEW

**Comment by edquist** [comment]
I've dropped the second paragraph.  As for the first one, it sounds almost intentionally subjective and up to the admin to determine what that means for them.

**Comment by brianhlin** [comment]
Some subjectivity is fine but we should provide some ballpark figures or heuristics as guidelines.

**Comment by DrDaveD** [comment]
I am sorry about the delayed response, you caught me on a couple of days of vacation.

You could say "sites that have more than a few hundred cores" instead of "large sites".  Instead of saying "it may be best", say "it is best".

**Comment by DrDaveD** [comment]
Although on second thought it depends on if someone supports CMS or ATLAS, where the Frontier application is, because that puts a much bigger load on squids.  If they only need it for cvmfs, they can probably get a way with quite a few more job slots.  So maybe it is better to leave it vague, unless you want to go into a lot of detail.  It also depends on how powerful the CE is.

**Comment by brianhlin** [comment]
I think that's knowledge we should impart to our users. Perhaps we can say something like this:

> For sites that have more than a few hundred cores, it is best to run the proxy on its own host. For sites that support LHC VOs, this core threshold is lower.

**Comment by DrDaveD** [comment]
When I was referring to a few hundred cores, I was including Frontier.  And it depends on if the CE host has a gigabit interface or 10-gigabit interface.  For cvmfs only, the caching is done per node, so the spec should be per node rather than per core; Frontier is generally per core, but actually it's per job slot so multi-core jobs require less bandwidth.  It's really too complicated to write out.  It's probably best to leave the current vague statement and advise people to monitor the network usage on the CE and if it regularly peaks at over a third of the bandwidth capacity then move the squid to a separate host.

**Comment by brianhlin** [comment]
Perfect, that's the sort of heuristic I was looking for! How's this?

> For large sites that expect heavy load on the proxy, it is best to run the proxy on its own host.
> If you are unsure if your site qualifies, we recommend iniitially running the proxy on your CE host and monitoring its bandwidth.
> If the network usage regularly peaks at over one third of the bandwidth capacity, move the proxy to a new host.

**Comment by DrDaveD** [comment]
That should be OK.

**Comment by brianhlin** [comment]
@edquist [make it so](https://www.youtube.com/watch?v=sZt6eU5REN8)

**Comment by edquist** [comment]
Will do, without the alternate spelling of "initially".

**Pull request merged**
