### PR TITLE
Change goc@ to help@ for support-related requests.

### PR DESCRIPTION
**Pull request by bbockelm**
It is believed to be more self-evident what one would find at `help@opensciencegrid.org`.

### CODE REVIEW

**Comment by bbockelm** [comment]
Looks like the failures were due to `linkchecker` hitting a rate limit at FNAL?

**Comment by brianhlin** [comment]
@RobQuickIU: I like help@opensciencegrid.org vs support@opensciencegrid.org. Thoughts?
@kagross: Did we verify that help@opensciencegrid.org forwards mail to goc@opensciencegrid.org?

**Comment by osg-cat** [comment]
Both help@ and support@ are mailing lists at Fermilab. Each one has a single subscriber, which is goc@.

**Comment by kagross** [comment]
But, also, goc@ is not receiving email to these lists from what I can tell.  Could you make me the owner of them please?

 

Kyle Gross

Open Science Grid Operations

Operations Support Manager

Indiana University Research Technologies

**Comment by osg-cat** [comment]
@kagross done.

**Comment by bbockelm** [comment]
@kagross - I added the "do-not-merge" label to this PR until we have a confirmation that mail to `help@` goes through.

**Pull request merged**
