### PR TITLE
stashcache: Replace reference to condor service with systemd timer

### PR DESCRIPTION
**Pull request by jthiltges**
Bring docs into line with changes merged in opensciencegrid/StashCache-Daemon#12

### CODE REVIEW

**Comment by bbockelm** [comment]
@jthiltges - what's the status of this one?

**Comment by jthiltges** [comment]
I think we're good to review and merge.

**Comment by matyasselmeci** [comment]
If I have an old version installed that still used condor to do the reporting, what do I need to do when upgrading?

**Comment by bbockelm** [comment]
@matyasselmeci - I think stopping the HTCondor service & disabling on boot is sufficient.  I think there's minimal overlap between "normal" HTCondor installs and StashCache instances.

There's no harm in having both running.

Probably worth noting in the release notes but I'm reluctant to have any technical mechanisms.

**Comment by matyasselmeci** [comment]
We don't have to explain mechanisms, just required user actions for everything to keep working as expected.

**Comment by brianhlin** [comment]
Hasn't the relevant version of StashCache already been released? Can we just merge this change?

**Comment by matyasselmeci** [comment]
sure.

**Pull request merged**
