### PR TITLE
Make ITB header red

### PR DESCRIPTION
**Pull request by brianhlin**
It works: https://opensciencegrid.github.io/docs-itb/

Corresponding submodule commit: https://github.com/opensciencegrid/doc-ci-scripts/commit/86fd2970d18fa4bdd7763b69c017449a8fc2b43b

### CODE REVIEW

**Comment by bbockelm** [comment]
Ha -- unless it's on mobile.  Then it doesn't!

There might be another CSS style you need to tweak?

**Comment by bbockelm** [comment]
Try setting class `wy-nav-top` property `background` to red also maybe?

**Comment by brianhlin** [comment]
Should be fixed now

**Comment by brianhlin** [comment]
Ok that was the easy bit. Adding some sort of warning header to every page -- I'm not sure how to do that.

**Comment by bbockelm** [comment]
How about something like this: https://stackoverflow.com/questions/40853308/watermark-text-repeated-diagonally-css-html

**Comment by brianhlin** [comment]
Oh god, it's so ugly. It could work but I was hoping to link to the actual docs

**Pull request merged**
