### PR TITLE
Add link to PATh grant in the footer

### PR DESCRIPTION
**Pull request by brianhlin**

### CODE REVIEW

**Comment by brianhlin** [comment]
Hey @CannonLock, BrianB asked me to have you review this change. Here's yet-another-website that we run: this one is for OSG site administrator documentation and we build it with MkDocs and serve it through GitHub pages

**Review by CannonLock — APPROVED** [review]
Perfect. Sorry about the long review, I had not previously used mkdocs so it took a bit to preview.

**Comment by brianhlin** [comment]
No worries! I'm not sure how you've got things setup but if you've got Docker installed, we've got some instructions for previewing the pages: https://opensciencegrid.org/technology/documentation/writing-documentation/#contributing-content

**Comment by brianhlin** [comment]
Link failure unrelated, merging

**Comment by CannonLock** [comment]
I managed to get it, thank you!

**Pull request merged**
